name: demo                                                                          # Name of this workflow

on:
  push:                                                                             # Specifies that this workflow should run on every push event for the branches in the list
    branches:
      - "main"

jobs:                                                                               #  Creates a job ID (build) and declares the type of machine that the job should run on
  build-demo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .                                                                  # Build Context
          file: ./Dockerfile                                                          # File path to Dockerfile
          push: true                                                                  # Tells the action to upload the image to a registry after building it
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest                     # Tags that specify where to push the image
